name: GitHub-Actions-Matrix-Run
on: push

jobs:  
  job1:
   runs-on: [windows-latest]
   steps:
      - name: Log node version
        id: identify
        run: |          
          $jsonBase = @{}
          $list = New-Object System.Collections.ArrayList

          $runners = "windows-latest,ubuntu-latest"
          $runnerList = $runners.split(",")
          
          foreach($runner in $runnerList){
            $list.Add(@{"runs_on"="$runner";"runsonbranch"="always";})
          }      

          $jsonBase.Add("Data",$list)
          $jsonBase | ConvertTo-Json -Depth 10
          
   
  node-versions:
    needs: [job1]
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest,ubuntu-latest1 ]
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: Log node version
        run: node -v
  job2:
   needs: [node-versions]
   runs-on: [windows-latest]
   steps:
      - name: Log node version
        id: identify
        run: |          
          node -v
