name: YamlWorkflowValidator

on:

  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:

  yaml-validation:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: 'Checkout repository on branch: ${{github.REF}}'
        uses: actions/checkout@v2
        with:
           ref: ${{ github.REF }}
           fetch-depth: 0
           
      - name: Checkout Repo Main Branch
        id: checkout_repo_main_branch
        uses: actions/checkout@v2
        with:
          repository: Aman-Angrish/MVCAzureDemo
          token: ${{ secrets.GIT_PAT }}
          path: YamlAdminCheckout
          ref: master
          fetch-depth: 0
    
      - name: Checkout Repo Feature Branch
        id: checkout_repo_feature_branch
        uses: actions/checkout@v2
        with:
          repository: Aman-Angrish/MVCAzureDemo
          token: ${{ secrets.GIT_PAT }}
          path: YamlAdminCheckout_Feature
          ref: ${{github.REF}}
          fetch-depth: 0
          
      - run: |
          pwd
          cd YamlAdminCheckout/.github/workflows
          ls -lart
          
#       - name: Setup
#         run: |
#           export PATH="/usr/bin/python3/bin:$PATH"
#           sudo python --version
#           sudo apt-get update
#           sudo apt-get --qq -y install pip
#           sudo apt-get install unixodbc-dev -y
#           sudo pip install pyodbc
#           sudo pip install deepdiff
#           sudo pipinstall pyyaml
#           sudo apt-get install -y zip unzip

      - name: Setup
        run: |
          export PATH="/usr/bin/python3/bin:$PATH"
          sudo python --version
          sudo apt update
          sudo apt -y install pip
          sudo apt install unixodbc-dev -y
          sudo pip install pyodbc
          sudo pip install deepdiff
          sudo apt install python-yaml          
          sudo apt install -y zip unzip
          
      - name: Execute Script
        run: |
          chmod 777 .github/scripts/yaml_validation.py
          python3 .github/scripts/yaml_validation.py "/home/runner/work/MVCAzureDemo/MVCAzureDemo/YamlAdminCheckout/.github/workflows/YamlWorkflowValidator.yml" "/home/runner/work/MVCAzureDemo/MVCAzureDemo/YamlAdminCheckout_feature/.github/workflows/YamlWorkflowValidator.yml"
